"""create jobs table

Revision ID: f783c1d0b760
Revises: 
Create Date: 2026-03-16 14:03:13.982718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f783c1d0b760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('url_hash', sa.String(length=16), nullable=False),
    sa.Column('slug_hash', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('knocked_out', sa.Boolean(), nullable=False),
    sa.Column('knockout_reason', sa.Text(), nullable=True),
    sa.Column('score_tech_stack', sa.Integer(), nullable=True),
    sa.Column('score_role_fit', sa.Integer(), nullable=True),
    sa.Column('score_work_auth', sa.Integer(), nullable=True),
    sa.Column('score_interviewability', sa.Integer(), nullable=True),
    sa.Column('score_ai_signal', sa.Integer(), nullable=True),
    sa.Column('score_growth', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('llm_scored', sa.Boolean(), nullable=False),
    sa.Column('llm_scored_at', sa.DateTime(), nullable=True),
    sa.Column('alerted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_slug_hash'), 'jobs', ['slug_hash'], unique=False)
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.create_index(op.f('ix_jobs_url_hash'), 'jobs', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_url_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug_hash'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
